### ISSUE TITLE
Need proxy configuration

### ISSUE THREAD

**Issue by santoshoommen** [d-fischer/twitch#103]
## Feature Request

Would be great if we can define an outbound proxy configuration as the module isn't able to route requests if the app is hosted behind a proxy for outbound connections

**Comment by d-fischer** [comment]
I'm finally working on this! 🎉 

The branch [feature/proxy-support](https://github.com/d-fischer/twitch/tree/feature/proxy-support) contains the necessary changes to allow API calls, chat connections (WS only) and PubSub connections via proxy (through a custom HTTP agent). Is there anything else necessary?

**Comment by santoshoommen** [comment]
Cheers. Thank you.
