### ISSUE TITLE
When using ClientCredentialsAuthProvider it tries to get access token with scope

### ISSUE THREAD

**Issue by Llorx** [d-fischer/twitch#104]
This simple code fails:

    let twitch= TwitchClient.withClientCredentials(config.twitch.id, config.twitch.secret);
    let client = ChatClient.forTwitchClient(twitch);
    client.connect();

It tries to get an access token with scope, when the login is with credentials, which don't have any scope.

I just would like to login using the typical `oauth:PASSWORD` method created with this tool: https://twitchapps.com/tmi/

**Comment by d-fischer** [comment]
Failing is the correct outcome here, as client credentials (client ID + client secret) have no way to be associated with a user. 

If you want to pass an access token directly, use `withCredentials` instead. 

Please note that 3rd party token generators are designed for development use and are not recommended for production. You are advised to roll your own OAuth flow where you have control over token refreshing and other details.
