### ISSUE TITLE
'allChatters' is empty if called more often than once per minute

### ISSUE THREAD

**Issue by hadmaerd** [d-fischer/twitch#105]
### Code

```JavaScript
// repeatedly calling this
var chatData = await twitchClient.unsupported.getChatters (channelName);
```

### Expected behavior

chatData.allChatters contains valid actual or cached list of users in the chat

### Actual Behavior

chatData.allChatters is empty if it's been less than 1 minute since last query

**Comment by d-fischer** [comment]
I just checked it with this code:

```ts
const twitch = TwitchClient.withClientCredentials(clientId, clientSecret);

(async () => {
	console.log((await twitch.unsupported.getChatters('thijs')).allChatters.length);

	await new Promise(resolve => setTimeout(resolve, 1000));

	console.log((await twitch.unsupported.getChatters('thijs')).allChatters.length);
})();
```

Please provide additional info, like your environment details (which was in the issue template for you to fill...)

**Comment by d-fischer** [comment]
After discussion on Discord, it was found that the chatters list was mutated, and that was the problem because the result of `ChattersList#allChatters` is cached. I removed that cache.
