### ISSUE TITLE
Sourcemaps are shipped via NPM without the actual source

### ISSUE THREAD

**Issue by Adam13531** [d-fischer/twitch#112]
### Bug Report

In `node_modules/twitch/lib`, there are files like `index.js.map`, `TwitchClient.js.map`, etc., but the corresponding source code isn't shipped. When debugging, it leads to errors like this:

![image](https://user-images.githubusercontent.com/7192897/75583154-f3dd2b00-5a21-11ea-995f-a463a1488b74.png)

### Expected behavior

I would expect either that sourcemaps *aren't* shipped or that source *is* shipped.

### Additional notes

As a workaround, I cloned this repo and copy/pasted the `src` folder directly into `node_modules/twitch`.

### Environment

- Version: 4.0.2

**Comment by d-fischer** [comment]
IIRC there's a TypeScript flag that inlines the source inside the source map. Would that be sufficient?

**Comment by Adam13531** [comment]
> IIRC there's a TypeScript flag that inlines the source inside the source map. Would that be sufficient?

I've unfortunately forgotten most of the context around this and no longer work with the codebase that caused me to file this issue. I think this comes down to your opinion on how to proceed. If it were my repository, I probably wouldn't ship sourcemaps at all, but I don't know what people expect here (I definitely *didn't* expect to have sourcemaps but no source).

**Comment by d-fischer** [comment]
After careful consideration, I decided to drop source maps completely instead. As such, this is "fixed" as of 4.1.0-pre.5 (0610f072).
