### ISSUE TITLE
Calling createStreamMarker() always(?) results in HTTP 400

### ISSUE THREAD

**Issue by epiblitikos** [d-fischer/twitch#118]
[Function definition exhibiting the bug.](https://github.com/d-fischer/twitch/blob/8b99a95ff40cd3ae3fa2eaa496a7b371695d5396/packages/twitch/src/API/Helix/Stream/HelixStreamAPI.ts#L189)

[The related API call](https://dev.twitch.tv/docs/api/reference#create-stream-marker) requires a Twitch user ID in parameter `user_id`, but it doesn't look like the code provides it. I was able to work around the 400 by hardcoding `query: {user_id: <MY TWITCH USER ID>,` into the `callAPI<...>` options. Once the correct parameter is the supplied, the call seems to function correctly through all later steps.

The specific call that produced the HTTP 400 was:
```js
twitchClient.helix.streams.createStreamMarker().then(
    () => nodecg.log.info("marker created")
).catch(reason => nodecg.log.info(`marker not created ${reason}`));
```
The call resulted in this output:
```
marker not created HTTPStatusCodeError: Encountered HTTP status code 400: Bad Request

Body:
{
  "error": "Bad Request",
  "status": 400,
  "message": "The parameter \"user_id\" was malformed: invalid value"
}
```

**Comment by epiblitikos** [comment]
It's perhaps also worth noting that the API accepts a `description` parameter, so the markers can be more easily delineated when read later.

**Comment by epiblitikos** [comment]
(Sorry for rapid fire...)
Another thing I realized as I finished adding the functionality I wanted to my bot: it's definitely useful to make markers on a user other than the one the app is operating under, *e.g.* I set my bot's user as a channel editor for my channel so it can make markers for me when I take and return from breaks.

**Comment by d-fischer** [comment]
For making requests as different users, you need to create multiple TwitchClient instances.
The userId and description parameters will be added in a patch release soon - it's technically a breaking change, but this currently doesn't seem to work at all, so I think it's fine.

**Comment by epiblitikos** [comment]
Thanks for the quick fix!
