### ISSUE TITLE
"TypeError: TwitchClient.withCredentials is not a function"

### ISSUE THREAD

**Issue by garyking** [d-fischer/twitch#12]
I have a very simple script, just to test this package. Yet it doesn't work. I'm getting `TypeError: TwitchClient.withCredentials is not a function`.

Only `twitch` is installed in `package.json`.
I have this:

```js
const TwitchClient = require('twitch');

const accessToken = '...';
const clientId = '...';

const twitchClient = TwitchClient.withCredentials(clientId, accessToken);
```

**Comment by d-fischer** [comment]
`TwitchClient` is the default ES module export. If you want to use it with `require()`, you need to use `require('twitch').default`.

**Comment by garyking** [comment]
Okay thanks. First time I've ever seen a package require `.default`. I guess most of them transpile first?

**Comment by d-fischer** [comment]
Modern JS users use ES modules, which then works just like it's shown in the README.

**Comment by garyking** [comment]
ES modules don't work on the LTS version of Node though, which is probably
the most common version, so any server-side code that I write with this
package can't use that, unfortunately.
