### ISSUE TITLE
Add getChannelTeams to ChannelAPI

### ISSUE THREAD

**Issue by talk2MeGooseman** [d-fischer/twitch#124]
## Feature Request

I noticed that an API endpoint I need, [Get Channel Teams](https://dev.twitch.tv/docs/v5/reference/channels#get-channel-teams) under the `Channel` entity was missing.

I would like to add this request under `ChannelAPI` class. I can implement it myself using the existing work done for `TeamAPI` class for the response object.

**Comment by d-fischer** [comment]
Sure, you're very welcome to add it :) if you do, please work on the `next` branch :)

**Comment by d-fischer** [comment]
Closing as #125 is already merged.
