### ISSUE TITLE
ChatUser: Name gets converted to lower case

### ISSUE THREAD

**Issue by schw4rzlicht** [d-fischer/twitch#130]
Hey there!

I am currently building a Twitch bot that should mention users in the chat. I realised that when getting `TwitchPrivateMessage.userInfo.name`, the name is always lower case and found the reason in the constructor of `ChatUser`:

https://github.com/d-fischer/twitch/blob/5aa61bc2195167e2cdf3434bd1eb5d0e335e81da/packages/twitch-chat-client/src/ChatUser.ts#L10

I am aware that my handler gets the correct name as argument from `ChatClient.onPrivmsg` but I am wondering why there is a need to convert in the first place. When converting it introduces the need of passing on a seperate argument for data that is already present 🤔

**Comment by d-fischer** [comment]
This is just a safeguard against certain Twitch oddities that happened in the past. This variable should already be lower case. The `toLowerCase` can probably be removed, but this will still be lower case. (The `user` argument of the event is also all lower case. Both are the exact same data.)

The `displayName` contains the name with the preferred casing, but also may contain special characters like certain Asian charsets or spaces, so it's not suitable for a @mention.

If you @mention someone, Twitch converts the name to the preferred display name case in the on-site chat anyway, so just use this.

If you don't want to @mention but still want to preserve their preferred display name, use `msg.userInfo.displayName`. If you want to prevent the special character cases, something like this should work:

```js
const preferredName = user === msg.userInfo.displayName ? msg.userInfo.displayName : user;
```
