### ISSUE TITLE
Kraken: implement Video API  ( or at least the features that aren't supported by the new API yet )

### ISSUE THREAD

**Issue by Technikkeller** [d-fischer/twitch#131]
## twitchClient.kraken.video Endpoints
I would suggest implementing twitchClient.kraken.video, especially the following methods as they aren't implemented by the new Twitch api yet:
- [Create Video](https://dev.twitch.tv/docs/v5/reference/videos#create-video)
- [Upload Video Part](https://dev.twitch.tv/docs/v5/reference/videos#upload-video-part)
- [Complete Video Upload](https://dev.twitch.tv/docs/v5/reference/videos#complete-video-upload)
- [Update Video](https://dev.twitch.tv/docs/v5/reference/videos#update-video)
- [Delete Video](https://dev.twitch.tv/docs/v5/reference/videos#delete-video)

As soon as they are implemented by the new twitch api they are obsolete, I know, but it would be really helpful to have them until then. 

Greetings Justus :D

**Comment by Vaeb** [comment]
The ability to delete videos would definitely be useful!

**Comment by d-fischer** [comment]
As discussed on Discord, until this is implemented, please use `TwitchClient#callAPI` as a substitute for any endpoint you need which is not yet implemented as a separate method; for example, for deleting a video:

```js
client.callAPI({
  url: `videos/${videoId}`,
  method: 'DELETE',
  scope: 'channel_editor'
});
```

**Comment by d-fischer** [comment]
Also, minor nitpick:

All sections referring to entities are named in plural, so it should be `twitchClient.kraken.videos`.
