### ISSUE TITLE
Enable passing a custom `hostName`

### ISSUE THREAD

**Issue by trezy** [d-fischer/twitch#132]
### Code

https://github.com/d-fischer/twitch/blob/0d1bd5b8f7583d7b3f3b77d2edf26c69f3b21cf9/packages/twitch-chat-client/src/ChatClient.ts#L645

### Expected behavior

The `twitch` lib will connect to whatever `hostName` I pass in.

### Actual Behavior

The `twitch` lib always connects to the hardcoded `hostName` in the library.

### Environment

- Version: 4.0.10

### Why?

Currently, it's not possible to use `twitch` with the [`fdgt`](https://fdgt.dev) API to simulate Twitch events. The library should be able to take a custom `hostName` to allow users to point their apps at `fdgt` for testing purposes.

**Comment by d-fischer** [comment]
This is not a bug report, it's a feature request.
