### ISSUE TITLE
Implement new Helix endpoints

### ISSUE THREAD

**Issue by d-fischer** [d-fischer/twitch#135]
## Feature Request

All these missing Helix endpoints should be implemented.

- [x] Get Channel Information
- [x] Modify Channel Information
- [x] Search Channels
- [x] Search Categories
- [x] Get Stream Key
- [x] Start Commercial
- [x] Create User Follows
- [x] Delete User Follows
- [x] Get Cheermotes
- [x] Get Hype Train Events (#175)
- [x] Hype Train WebHook (#175)
- [x] Create Custom Rewards
- [x] Delete Custom Reward
- [x] Get Custom Reward
- [x] Get Custom Reward Redemption
- [x] Update Custom Reward
- [x] Update Redemption Status

**Comment by billygerhard** [comment]
Also the new Event Sub endpoints: https://dev.twitch.tv/docs/eventsub/helix-endpoints

[] Create EventSub Subscription 
[] Delete EventSub Subscription
[] Get EventSub Subscriptions

**Comment by d-fischer** [comment]
Thanks, I added the channel point endpoints here and the EventSub endpoints to #184.

**Comment by d-fischer** [comment]
Released the currently checked methods (all except extensions and rewards/redemptions) in 4.3.0-pre.6. The mentioned exceptions will follow the next few days.

**Comment by d-fischer** [comment]
Removed the user extension endpoints from this because they need more consideration about their input and output formats. Please track #185 and/or submit feedback about how these formats could look like.
