### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by garyking** [d-fischer/twitch#14]
Are there any docs anywhere for the methods found in this package? Or should I just browse the code itself?

**Comment by erei** [comment]
Docs are being worked on, there have been occasional updates on them over at the [Twitch API Discord server](https://discordapp.com/invite/b9ZqMfz).

**Comment by d-fischer** [comment]
There are also already issues opened by myself for the docs, so I'm gonna close this as a duplicate of #4 and #5.
