### ISSUE TITLE
Normalize `_id` and `_data`

### ISSUE THREAD

**Issue by garyking** [d-fischer/twitch#15]
Any chance that `_id` and `_data` could be normalized so that `id` and `data` would also work?

Or is this package intending on 100% mirroring the Twitch API response with these values? I don't understand what the purpose of the underscore is, in both this package and the API response?

**Comment by d-fischer** [comment]
Underscores at the beginning of member names are a convention that they are not to be relied on, as they're supposed to be private. As JavaScript has no concept of "private" right now, they're obviously still usable, but you shouldn't.
Please use the supplied getters. If you need to get some data that is missing a getter, open an issue or a PR for that.
