### ISSUE TITLE
Make refresh webhooks subscriptions optional

### ISSUE THREAD

**Issue by motia** [d-fischer/twitch#155]
## Feature Request

I am trying to using the webhooks package in a FaaS setting.
As the subscriptions are refreshed automatically, the process does not want to exit immediately.

Is it possible to make the refresh opt-in optional?
For example, by adding a setting a boolean to `WebhookListner` that decides whether the `Subscription.start` should dispatch the refresh or not. For BC, we can set the auto-refresh as the default behavior.

I will be happy to help implementing it.

Thanks.

**Comment by d-fischer** [comment]
I don't think you want to use the `twitch-webhooks` library then. It will keep up the process to listen to the actual events by spinning up its own HTTP server.

If you want to use serverless functions, you may want to use the `client.helix.webHooks` methods of the `twitch` library instead.

**Comment by motia** [comment]
Thanks for the quick answer.

I am already using the methods you mentioned. I wanted to refactor this to be able the `WebhookListener` validation functions. At a second thought it is not very complicated to extract the necessary code.
