### ISSUE TITLE
Get users by ids and names returns requester

### ISSUE THREAD

**Issue by robhunt3r** [d-fischer/twitch#157]
## Bug Report
Using latest version 4.20-pre4 calling `client.helix.users.getUsersByIds` and `client.helix.users.getUsersByNames` with an empty array as a value, returns an array result containing the requester itself.

### Expected behavior

Return empty array or throw an exception

### Actual Behavior

Returns an array containing the requester itself, making all validations act weird because either the promise should crash or the result should be an empty array.

### Environment

- Version: 4.2.0-pre.4
- Node version: 14.5.0
- Operating system: Linux

**Comment by iProdigy** [comment]
This is a documented feature of the Twitch API itself rather than a library bug: https://dev.twitch.tv/docs/api/reference#get-users

**Comment by robhunt3r** [comment]
Oops! Sorry then. Closing.

**Comment by d-fischer** [comment]
No, it's a valid point for the library.

There's a separate method (`getMe`) for getting the requester. A method that advertises getting users by ID or name shouldn't magically get something else when you pass it nothing.

**Comment by robhunt3r** [comment]
Yeah @d-fischer that's what I was thinking when opened the bug, but I didn't know it was a Twitch issue. Yeah it would be very helpful in the library.

Also for some tests I've dome, `getUsersByNames` also accepts ids (like Twitch does) so I think it would be also helpful to either combine both into one single call.

**Comment by d-fischer** [comment]
> but I didn't know it was a Twitch issue

It's not an *issue*. It's an explicit feature.

> `getUsersByNames` also accepts ids (like Twitch does)

It does not, and neither does Twitch. Different query parameters are passed/required in the two different cases.
If you pass an ID to `getUsersByNames`, it won't find anything.

**Comment by d-fischer** [comment]
This should be fixed on the `master` branch. Please check out the prerelease version `4.2.0-pre.7` to check.
