### ISSUE TITLE
Remove listenerPort from CommonConnectionAdapterConfig and add it to listen

### ISSUE THREAD

**Issue by Technikkeller** [d-fischer/twitch#158]
## Feature Request

Because you can use .applyMiddleware for WebHookListener instead of .listen() since 4.1, the port isn't required anymore in that case and should therefore be moved to the listen method instead. 

I would make the port a optional param in 4.x but still use it as default in .listen, so it isn't breaking, but throw a deprecation warning in the console, and then remove it entirely in 5.0.

**Comment by d-fischer** [comment]
Any idea how this could work with adapters that define their own listener port instead of taking one as configuration parameter, like `EnvPortAdapter` or `NgrokAdapter`?

**Comment by d-fischer** [comment]
I have implemented a form of this in `twitch-eventsub`. Not doing any active development on `twitch-webhooks` anymore, it's in maintenance mode starting with 4.4.
