### ISSUE TITLE
ChatSubGiftInfo plan and gift lenght

### ISSUE THREAD

**Issue by that1estonian** [d-fischer/twitch#159]
## Feature Request

Getting the plan info and gifted sub lenght with ChatSubGiftInfo would be awesome :)

**Comment by d-fischer** [comment]
Gift sub length was added on the `master` branch. Please check out the prerelease version `4.2.0-pre.7` to check.

Where are you missing the plan info? I wasn't able to find an event where Twitch provides any plan info the objects don't already expose.

**Comment by that1estonian** [comment]
Thanks for all the work!

About the plan info tho. From documentation, ChatSubGiftInfo provides this information:

gifter?: string
gifterDisplayName?: string
gifterGiftCount?: number
gifterUserId?: string

But I get it, if it's a Twitch thing. Just seemed weird, since all other sub events also provide the plan info 🤷‍♂️
