### ISSUE TITLE
Documentation Issue in Basic Bot page

### ISSUE THREAD

**Issue by joezeng** [d-fischer/twitch#162]
On the [Basic bot](https://d-fischer.github.io/twitch-chat-client/docs/examples/basic-bot.html) page, under the heading "Create an `ApiClient` instance", no `ApiClient` instance is actually created. Instead, it appears the `StaticAuthProvider` is being passed directly into the `ChatClient` constructor, which doesn't actually work when I tried it.

**Comment by d-fischer** [comment]
The interface of the `ChatClient` constructor is:

```ts
constructor(authProvider: AuthProvider | undefined, options?: ChatClientOptions);
```

So the code in the steps is correct (I spotted a mistake in the summary though), but the text is wrong. I'll change that and close the corresponding PR.

**Comment by joezeng** [comment]
Huh, okay. For some reason my change worked, but I guess the text was misleading.

**Comment by d-fischer** [comment]
What you are reading is the documentation for the upcoming 4.2 version, which is currently in a prerelease state. A clarifying update for the docs is in the works.

You have two options:
```
npm i twitch-auth@next twitch-chat-client@next
```
or check the [4.1 docs](https://d-fischer.github.io/branches/support/4.1/twitch-chat-client/docs/examples/basic-bot.html).

**Comment by joezeng** [comment]
Thanks for the clarification, I'll be using the 4.1 docs from now on.
