### ISSUE TITLE
Add User Extension Endpoints

### ISSUE THREAD

**Issue by billygerhard** [d-fischer/twitch#167]
## Feature Request

- [ ] Get User Extensions https://dev.twitch.tv/docs/api/reference#get-user-extensions
- [ ] Get User Active Extensions https://dev.twitch.tv/docs/api/reference#get-user-active-extensions
- [ ] Update User Extensions https://dev.twitch.tv/docs/api/reference#update-user-extensions

**Comment by d-fischer** [comment]
I just incorporated these endpoints into #135, thus I am closing this as duplicate as we don't need multiple tickets for adding Helix endpoints.
