### ISSUE TITLE
pubSubClient.onModAction does only properly work for a single channel listener

### ISSUE THREAD

**Issue by Rydann** [d-fischer/twitch#176]
## Bug Report
pubSubClient.onModAction does only properly fire events for a single channel listener. Any additional listeners for different channels all fire a duplicate of the event of the last registered channel.

### Code
```JS
// Option 1:
let listeners = {};
for (i = 0; i < config.channels.length; i++) {
  let channel = config.channels[i];
  listeners[`${channel.id}-onModAction`] = await pubSubClient.onModAction(channel.id, (message) => {
    console.log(message);
  });
}

// Option 2:
pubSubClient.onModAction("71681674", (message) => {
  console.log(message);
});

pubSubClient.onModAction("495563548", (message) => {
  console.log(message);
});


/* output: (x2)
PubSubChatModActionMessage {
  _data: {
    type: 'moderation_action',
    data: {
      type: 'chat_login_moderation',
      moderation_action: 'ban',
      args: [Array],
      created_by: 'rydannn',
      created_by_user_id: '71681674',
      msg_id: '',
      target_user_id: '12427',
      target_user_login: '',
      from_automod: false
    }
  },
  _channelId: '495563548'
}
*/
```

### Expected behavior
Every listener should fire the corresponding channel's event instead of a duplicate of the last registered one.

### Actual Behavior
Every listener fires a duplicate of the event of the last registered listener.

### Environment

- Version: 4.2.2
- Node version: v12.14.1
- Operating system: Windows 10

**Comment by d-fischer** [comment]
Thanks for reporting - this was fixed in 4.2.3!
