### ISSUE TITLE
Calling ChatClient.removeListener breaks onMessage

### ISSUE THREAD

**Issue by daniel0611** [d-fischer/twitch#177]
## Bug Report

Calling `chatClient.removeListener()` breaks onMessage. Listeners that are created after this call using `chatClient.onMessage(...)` will never get called on a message.

__I'll try to create a PR fixing this shortly, this issue is just for reference.__

### Code

```ts
const chatClient: ChatClient = ... // creating ChatClient using the usual way
chatClient.removeListener();
chatClient.onMessage(() => console.log("A message has been received.")) // This handler never gets called
```

### Expected behavior

Newly created handlers using `onMessage` should get fired when a event occurs.

### Actual Behavior

The handler never gets called.

### Environment

- Version: 4.2.3

**Comment by d-fischer** [comment]
Fixed by #178.
