### ISSUE TITLE
Named args

### ISSUE THREAD

**Issue by garyking** [d-fischer/twitch#18]
Consider allowing named args rather than just positional arguments, for most methods. 

For instance, `users.getFollowedChannels(123, null, 100)` could be `users.getFollowedChannels(123, { limit: 100 }` or `users.getFollowedChannels({ user: 123, limit: 100 })` etc.

**Comment by d-fischer** [comment]
This style was already adopted for the Helix methods. I will not change it for the Kraken methods. There are not too many Kraken methods with more than, say, three arguments. Also this would unnecessarily break backwards compatibility.
