### ISSUE TITLE
Add simple IGDB Support

### ISSUE THREAD

**Issue by roncli** [d-fischer/twitch#180]
## Feature Request

This is a feature request to add simple IGDB support to twitch-api-call.

IGDB calls differ from other Twitch API calls in two ways:
* The IGDB API is accessed via a bearer authorization header with an access token retrieved through Twitch's client credential flow.
* It uses Apicalypse to query the data, which means it needs to send a raw body that is of content type `text/plain`.

Otherwise, these calls are identical to other calls of type `TwitchApiCallType.Custom`.

I've got an easy way to get this working in twitch-api-call by adding two optional properties to the TwitchApiCallOptions interface, `rawBody` and `authType`, and would be happy to discuss the implementation and create a pull request for it should you be interested.  You can find the implementation at https://github.com/roncli/twitch on the master branch.  Example usage:

```
const clientId = "0123456789ABCDEF";
const accessToken = "FEDCBA9876543210"; // Must get this via client credentials flow.

TwitchApi.callTwitchApi({
    authType: "bearer",
    method: "POST",
    rawBody: "search \"Descent\"; fields name;",
    type: TwitchApi.TwitchApiCallType.Custom,
    url: "https://api.igdb.com/v4/games"
}, clientId, accessToken);
```

**Comment by d-fischer** [comment]
I think this is out of scope for this library family. The API is only marginally related to Twitch - there are really just two things that it has in common with the Twitch APIs:

- The same owner. Not exactly a compelling reason to cram these together.
- The fact that it uses Twitch OAuth tokens. For that fact, it should be good enough to create a completely new library that maybe peer depends on `twitch-auth`. I am not ready to support this though - please create a new repository if you want to go that route.

**Comment by roncli** [comment]
I'm going to pass on creating a new repository... the extent to which I need to use it isn't large enough to warrant creating something that would require maintenance.  I've got enough maintenance on my hands at the moment. :)

My intention was to expand what you can do with `TwitchApiCallType.Custom`.  The scope of the change is small and generalized enough that it doesn't directly support IGDB like, say, the functions under `KrakenApiGroup`, rather it makes calling IGDB possible with `TwitchApiCallType.Custom`.  It just allows sending a raw body via text/plain and selecting the authorization type.    If you haven't reviewed the change on the repo, I encourage you to do so.

On the chance that someone may be looking for how to do this without modifying the library, I've opted to just make the call myself using `@root/request`, but still getting the accessToken through twitch-auth.  It's not that much more code, but it does require another dependency.

```
        const client = "0123456789ABCDEF";
        const accessToken = (await apiAuthProvider.getAccessToken()).accessToken;

        const res = await request({
            body: `search "${search.replace(/\\/g, "\\\\").replace(/"/g, "\\\"")}"; fields name;`,
            headers: {
                Authorization: `Bearer ${accessToken}`,
                "Client-ID": clientId,
                "Content-Type": "text/plain",
            },
            method: "POST",
            url: "https://api.igdb.com/v4/games"
        });

        return JSON.parse(res.body);
```

**Comment by d-fischer** [comment]
`twitch-api-call` is a very thin wrapper around the `fetch` API to support the use cases of the library family and nothing more. It was split out of the API client because of a circular dependency issue, not really to support any outside use.

Comparing your two code blocks, all the package would really do for you is to build the headers object.

**Comment by roncli** [comment]
That's good context for me to consider.  Thanks for providing!

**Comment by Shoheata** [comment]
thank you for helping me.
