### ISSUE TITLE
[twitch-webhooks] When call listen() quickly after unlisten(), the suspended subscriptions are not correctly resubscribed

### ISSUE THREAD

**Issue by GreenMonkeyBoy** [d-fischer/twitch#181]
### Info 

I use Ngrok but I don't use `twitch-webhooks-ngrok`, I connect with `ReverseProxyAdapter`.

### Code

```
this.webhooksListener = new WebHookListener(
    this.apiClient,
    new ReverseProxyAdapter({
        hostName: webhooksHostname,
        listenerPort: 8090
    })
)
```
### Actual Behavior

When I call `unlisten()`, I receive four requests over 100 seconds:
```
GET  /stream.change.120607238  502 Bad Gateway        
GET  /stream.change.120607238  502 Bad Gateway        
GET  /stream.change.120607238  502 Bad Gateway
GET  /stream.change.120607238  502 Bad Gateway
```
Then if I call `listen()`, I receive one request:
```
GET  /stream.change.120607238  202 Accepted 
```
And on each notification I receive a `POST 202` and all is working well:
```
POST /stream.change.120607238  202 Accepted
```

But if I call `listen()` before the fourth request (`502 Bad Gateway`), I receive two requests:
```
GET  /stream.change.120607238  200 OK
GET  /stream.change.120607238  202 Accepted
```
And now for the first next notification I receive a `POST 410`, and then no more notification:
```
POST /stream.change.120607238  410 Gone
```
And the console says:
```
twitch-webhooks WARNING Notification for unknown hook received: stream.change.120607238
```

### Environment

- Version:  
    "twitch": "^4.2.5",
    "twitch-webhooks": "^4.2.5",
- Node version: v14.8.0

**Comment by d-fischer** [comment]
This is fixed in 4.2.7 and 4.3.0-pre.4.
