### ISSUE TITLE
TwitchAuth.getAppToken should accept scopes

### ISSUE THREAD

**Issue by bradnak** [d-fischer/twitch#190]
## Feature Request

According to the [client credentials documentation](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-client-credentials-flow), the endpoint accepts an optional set of scopes, just like in user access tokens.
I was trying to use `TwitchAuth.getAppToken` to supply a scope (such as `channel:read:subscriptions`) to this endpoint, but one is not accepted.
Is this something that could be updated?

**Comment by d-fischer** [comment]
IIRC this is a Twitch documentation error. What do you think would be achieved by this?

Scopes enable you to get the data of the associated user of a token.
App access token have no directly associated user.
So this couldn't possibly give you any value.

**Comment by bradnak** [comment]
OK, so there must be other errors in Twitch's documentation as well because I was looking at the [EventSub documentation](https://dev.twitch.tv/docs/eventsub) which says:
> You must include an app access token in all API requests. You do not need to include a user access token, even for subscriptions that require user authorization.

but also that the [`channel.subscribe` event docs](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelsubscribe) says you need a `channel:read:subscription` token. If this my misinterpretation, then my mistake. By the way, I am aware you are working on an EventSub package but just picked that as a private project to do to test my skills. 😄

**Comment by d-fischer** [comment]
Scopes are handled differently in EventSub. They are checked globally, that means the scope is available if there was *ever* a user authorization to your application with the mentioned scope (that wasn't revoked).

From the EventSub docs, right after the part you quoted:
> This is because Twitch checks authorization throughout the lifetime of your subscription by calling Twitch’s internal authorization systems directly.

-----

> By the way, I am aware you are working on an EventSub package but just picked that as a private project to do to test my skills. 😄

You're welcome to contribute code or improvement possibilities to the structure and interface of the code! To discuss the latter, [Discord](https://discord.gg/b9ZqMfz) is the place to go.
