### ISSUE TITLE
Use status Channel Point API

### ISSUE THREAD

**Issue by GautheyValentin** [d-fischer/twitch#193]
## Feature Request

Hi, 

i wanted use Channel Point API but you implement status but you don't use in body 😥

Can i implement ? 

Thanks in advance

**Comment by d-fischer** [comment]
Thanks for reporting, this is fixed in 4.3.4.

**Comment by GautheyValentin** [comment]
> Thanks for reporting, this is fixed in 4.3.4.

Hi, sorry to disturb you again with this issue.
You just forget to update method : `updateRedemptionStatusByIds` to use status

Thanks in advance

**Comment by d-fischer** [comment]
Actually fixed in 4.3.5.
