### ISSUE TITLE
Get default image from Redeem

### ISSUE THREAD

**Issue by crutchcorn** [d-fischer/twitch#196]
## Feature Request

Currently, not all of my Twitch redeem items have images assigned to them (and many of them I'm using built-in-images from Twitch's default actions). As such, when trying to display `rewardImage.url_4x`, I occasionally get errors depending on what reward I am trying to redeem. As I am trying to build a public-facing tool, where other users might have this same problem, it would be ideal to expose the default images to the `PubSubRedemptionMessage` class

I have already made code changes related to this feature request and can open a PR if this feature is approved - I'm simply trying to follow the direction of the PR/Issue template and open an issue first

**Comment by d-fischer** [comment]
Thanks for spotting this! As this is not a major feature, please PR it to the `support/4.3` branch - it can then get a stable release very soon.

**Comment by d-fischer** [comment]
I published version 4.3.6 which includes your fix - thanks again!
