### ISSUE TITLE
PubSub listeners can't be removed

### ISSUE THREAD

**Issue by bartje321** [d-fischer/twitch#198]
## Bug Report
When registering PubSub listeners the topicName is generated using the type, userId and additional parameters. This is used as key in the listeners map. When removing the listener it looks up the map only on type, which won't exists because it's missing the userId and the additional parameters.

### Code
https://github.com/d-fischer/twitch/blob/45175a0d4e0ff9bc17410419a03abae179b84487/packages/twitch-pubsub-client/src/SingleUserPubSubClient.ts#L255

https://github.com/d-fischer/twitch/blob/45175a0d4e0ff9bc17410419a03abae179b84487/packages/twitch-pubsub-client/src/SingleUserPubSubClient.ts#L191

### Expected behavior
listener gets removed on calling `.remove();`

### Actual Behavior

Listener doesn't get removed and PubSub client won't disconnect.

### Environment

- Version: 4.3.5
- Node version: v14.10.0
- Operating system: MacOsx

**Comment by d-fischer** [comment]
Thanks for reporting and even doing some research! I published version 4.3.6 which should fix this.
