### ISSUE TITLE
Can't specify stream type for getFollowedStreams()

### ISSUE THREAD

**Issue by garyking** [d-fischer/twitch#20]
I can't seem to specify the stream type for getFollowedStreams(). I'm trying to use strings and the enums, but I can't seem to figure it out. 

Does it accept either string or enum? Or how do I use an enum for it?

I tried `'live'`, `twitch.StreamType.Live`, etc.

**Comment by d-fischer** [comment]
Please stop using this bug tracker as a support forum. Use the [Discord server](https://discord.gg/b9ZqMfz) instead, as pointed out in the README.
