### ISSUE TITLE
СhannelPoints getRedemptionsForBroadcasterPaginated getAll - throws 400 Bad Request

### ISSUE THREAD

**Issue by smashboy** [d-fischer/twitch#207]
### Code

```ts
const promises = rewardIds.map(async (rewardId) => {
      const redemptionsRequest = twitchApiClient.helix.channelPoints.getRedemptionsForBroadcasterPaginated(
        broadcasterId,
        rewardId,
        twitchCustomRewardRedemptionStatus,
        { newestFirst: true }
      );

      const broadcasredRedemptions = await redemptionsRequest.getAll();
      const parsedRedemptions2Contenders = twitchCustomRewardRedemptionsParser(
        broadcasredRedemptions
      );

      return parsedRedemptions2Contenders;
    });

    const contenders = (await Promise.all(promises)).flat();
```

### Expected behavior

Should return all redemptions .

### Actual Behavior

Throws bad request error that shows that parameter `first` is not formed correctly?
I was reqeusting 25 UNFULFILLED redemptions from one custom reward.

![image](https://user-images.githubusercontent.com/30213662/104189208-09352b00-5423-11eb-8e7d-a8e433a6778e.png)

### Environment

NextJS (v10.0.4) API Routes

- Version: 4.3.6
- Node version: 12.18.2

**Comment by d-fischer** [comment]
Heh, I guess I overlooked this. Normally, the `first` parameter can be up to 100. This endpoint seems to be one of the rare exceptions. I'll get a quick fix going as soon as I can.

**Comment by smashboy** [comment]
@d-fischer Thanks.

**Comment by d-fischer** [comment]
4.3.9 fixes this. Thanks for reporting!
