### ISSUE TITLE
EventSubChannelRedemptionUpdateEvent broadcaster/userName returns an empty string

### ISSUE THREAD

**Issue by kuroshiropanda** [d-fischer/twitch#210]
## Bug Report
`EventSubChannelRedemptionUpdateEvent` `broadcasterName` and `userName` properties returns an empty string

### Expected behavior
It should return the login name or username of the broadcaster/user

### Actual Behavior
It returns an empty string

### Environment

- Version: 4.4.2
- Node version: v15.6.0
- Operating system: Windows 10

**Comment by d-fischer** [comment]
This is a Twitch issue, please track https://github.com/twitchdev/issues/issues/299 instead.
