### ISSUE TITLE
Subscribing to an EventSub event previously subscribed to does sometimes throw a 409 error instead of resuming the subscription

### ISSUE THREAD

**Issue by salbeira** [d-fischer/twitch#214]
## Bug Report

As described in the title, after you shut down your event handling program and restart it, if you stored the events to subscribe to into persistant storage and then immediatly want to resume the subscription without much delay (as regularily happens when you do code fixes to your own project and then rapidly kill and restart your program), sometimes, but not always, the subscribeToXEvents function throws an error like this:

```
[HttpStatusCodeError: Encountered HTTP status code 409: Conflict

Body:
{
  "error": "Conflict",
  "status": 409,
  "message": "subscription already exists"
}] {
  _statusCode: 409,
  _body: {
    error: 'Conflict',
    status: 409,
    message: 'subscription already exists'
  }
}
```

It has no stack trace attached to it.

### Code

```ts
async resume() {
        const subs = await system.db.getTwitchUserIDs(); //Load users you want to watch going online from persistent storage
        for (const sub of subs) {
            try {
                const non = await this.listener.subscribeToStreamOnlineEvents(sub.twitch_user, e => {
                    notifyStreamerWentOnline(e.broadcasterDisplayName, e.broadcasterId);
                });
            } catch (error) {
                console.error(error);
                return;
            }
        }
    }

```

### Expected behavior

The EventListener simply resumes the subscription, as is like to happen when it works.

### Actual Behavior

The subscribe function throws said error.

**Comment by d-fischer** [comment]
This was technically an error in user code (didn't await on listen), but while adding the capability to register before listening, this automatically got fixed as well.
