### ISSUE TITLE
Helix HypeTrain API returns empty event objects

### ISSUE THREAD

**Issue by daniel0611** [d-fischer/twitch#215]
## Bug Report
All helix HypeTrain methods return objects that return `undefined` for all properties (e.g. level, startDate, expiryDate)

### Code

```ts
const twitch: ApiClient = ...
const myUser = await twitch.helix.users.getMe();
const { data } = await twitch.helix.hypeTrain.getHypeTrainEventsForBroadcaster(myUser);
data.forEach(hypeTrainEvent => {
    console.log(`Level: ${hypeTrainEvent.level}`);
    console.log(`Start: ${hypeTrainEvent.startDate}`);
});
```

### Expected behavior

It should log the level and start date of all recent hype trains.

### Actual Behavior

`level` and `startDate` are just undefined. This is also true for other properties like `expiryDate` or `total`.

### Environment

- Version: 4.3.0..4.4.6

I assume the current code exprects all properties to be in a object of the `data` array but given the [endpoint example response](https://dev.twitch.tv/docs/api/reference#get-hype-train-events) it seems that they are actually nested inside another sub-object `event_data`.

**Comment by d-fischer** [comment]
Fixed in 4.4.7.
