### ISSUE TITLE
Can't connect to 3 letter channels with ChatClient

### ISSUE THREAD

**Issue by mxrlkn** [d-fischer/twitch#221]
## Bug Report

When trying to use ChatClient from twitch-chat-client to connect to a chat, you can't connect to 3 letter channels like twitch.tv/lck or twitch.tv/lcs because of this rule: https://github.com/d-fischer/twitch/blob/d1cf5ed14ad4bc1ceb046e4f0e93809300e90ce1/packages/twitch-chat-client/src/Toolkit/UserTools.ts#L2

### Code

```js
import {ChatClient} from "twitch-chat-client";

const chatClient = new ChatClient(null, {channels: ["lck"]});
await chatClient.connect();
```

### Expected behavior

Expect to connect to chat without errors.

### Actual Behavior

Error when running the code above:

```
file:///app/node_modules/twitch-chat-client/es/Toolkit/UserTools.mjs:8
throw new Error("\"" + name + "\" is not a valid user or channel name. It must be 4-25 characters long, can only include letters, numbers and underscores, and can not start with an underscore.");

Error: "lck" is not a valid user or channel name. It must be 4-25 characters long, can only include letters, numbers and underscores, and can not start with an underscore.
```
### Environment

- Version: 4.4.8
- Node version: 15.5.0

**Comment by AlcaDesign** [comment]
There are 1 letter usernames so this should probably be reduced. For instance user `X`.
