### ISSUE TITLE
EventSub "subscribe to channel reward remove events" causing invalid subscription error

### ISSUE THREAD

**Issue by jayther** [d-fischer/twitch#225]
### Code

```js
const rewardRemoveSub = await eventSub.subscribeToChannelRewardRemoveEvents(userId, onRewardRemove);
```

### Expected behavior

Return a subscription object with no error.

### Actual Behavior

Fails to return a subscription object and throws a rejection with the following error:

```
HttpStatusCodeError: Encountered HTTP status code 400: Bad Request

Body:
{
  "error": "Bad Request",
  "status": 400,
  "message": "invalid subscription type and version"
}
```

### Cause of Error

In: https://github.com/d-fischer/twitch/blob/versions/4.4/packages/twitch/src/API/Helix/EventSub/HelixEventSubApi.ts#L349

Typo: `'channel.channel_points_custom_rewards.remove'`

Subscription type should be: `'channel.channel_points_custom_reward.remove'`

### Environment

- Version: 4.4.7
- Node Version: 12.16.1
- Operating system: Windows 10

**Comment by d-fischer** [comment]
I'm not sure why the merge didn't close this automatically, but this is fixed in 4.4.11. Thanks for reporting!
