### ISSUE TITLE
New EventSub Channel Ban/Unban Properties (Mod, reason, duration)

### ISSUE THREAD

**Issue by AlcaDesign** [d-fischer/twitch#226]
## Feature Request

New properties, from the Twitch change-log (2021‑02‑12):

- `EventSub Channel Ban` v1 now includes moderator information, reason for ban, and timeout duration if the ban was a timeout.
- `EventSub Channel Unban` v1 now includes moderator information.

**Comment by d-fischer** [comment]
Fixed by merging #227. Thanks for tracking the latest changes to the Twitch API 😄
