### ISSUE TITLE
api.helix.channels.startChannelCommercial should be a POST and the method is not defined in the request

### ISSUE THREAD

**Issue by MikeMayer** [d-fischer/twitch#228]
Hey there-

The helix API `startChannelCommercial` won't work because the method is defaulting to `GET`. It [should be a `POST`].(https://dev.twitch.tv/docs/api/reference#start-commercial). I've also temporarily modified my local copy of the library to include the method parameter in this call.

As seen here: https://github.com/d-fischer/twitch/blob/7721e45cfce2498dc93ac5b914a25c6e9bbf261e/packages/twitch/src/API/Helix/Channel/HelixChannelApi.ts#L90

**At the time of issue creation**
```javascript
async startChannelCommercial(broadcaster: UserIdResolvable, length: CommercialLength): Promise<void> {
		await this._client.callApi({
			type: TwitchApiCallType.Helix,
			url: 'channels/commercial',
			scope: 'channel:edit:commercial',
			jsonBody: {
				broadcaster_id: extractUserId(broadcaster),
				length: length
			}
		});
	}
```

We can easily resolve this by just including the method parameter as well as `POST`.

**Fix**
```javascript
async startChannelCommercial(broadcaster: UserIdResolvable, length: CommercialLength): Promise<void> {
		await this._client.callApi({
			type: TwitchApiCallType.Helix,
			url: 'channels/commercial',
                        method: 'POST',
			scope: 'channel:edit:commercial',
			jsonBody: {
				broadcaster_id: extractUserId(broadcaster),
				length: length
			}
		});
	}
```

**Comment by d-fischer** [comment]
Fixed in 0fee74df but forgot the "closes" statement. Also released with 4.4.12. Thanks for reporting!
