### ISSUE TITLE
HelixCustomReward 'prompt' property typo

### ISSUE THREAD

**Issue by Rydann** [d-fischer/twitch#231]
## Bug Report

As described in the title, the `prompt` property of `HelixCustomReward` is currently misspelled.

### Expected behavior

```get prompt(): string;```

### Actual Behavior

```get propmt(): string;```

### Environment

- Version: 4.5.0

**Comment by d-fischer** [comment]
Good catch! I will handle this like this:
- Add `prompt` to 4.5
- Deprecate `propmt` in 4.5
- Remove `propmt` in 5.0
