### ISSUE TITLE
Typo & false warning condition check in ChatClient.whisper()

### ISSUE THREAD

**Issue by Rydann** [d-fischer/twitch#247]
### Code

```ts
async whisper(user: string, message: string): Promise<void> {
	if (!this._needToShowWhisperWarning) {
		this._needToShowWhisperWarning = false;
		this._chatLogger.warn(
			`You did not set a botLevel option.
Pleasae note that your whispers might not arrive reliably if your bot is not a known or verified bot.`
		);
	}
	return this._whisperRateLimiter.request({
		target: toUserName(user),
		message
	});
}
```

### Expected behavior

When a correct `botLevel` is set `_needToShowWhisperWarning` will have a value of `false`.
The condition check above should therefore only become true if the value of `_needToShowWhisperWarning` is also `true`.

_Also there's a typo: `Pleasae` should be `Please`._

### Actual Behavior

The exact opposite happens, which causes a warning to be issued when a correct `botLevel` is set.

### Environment

- Version: 4.5.2

**Comment by d-fischer** [comment]
PR merged, thanks for the fix!
