### ISSUE TITLE
Add HypeTrain cooldown_end_time

### ISSUE THREAD

**Issue by greebowarrior** [d-fischer/twitch#251]
## Feature Request

It seems the only property that hasn't been implemented in HelixHypeTrainEvent is the cooldown_end_time, and this is the one I needed XD
I've already made a change, please let me know when I can submit a PR: https://github.com/greebowarrior/twitch/tree/patch-1

**Comment by d-fischer** [comment]
It's fine to create a PR. I haven't looked at the code itself, but please base the changes on the `version/4.5` branch.

**Comment by d-fischer** [comment]
Fixed by #252 and released with 4.5.4.
