### ISSUE TITLE
Get follow time in ChannelFollow

### ISSUE THREAD

**Issue by T1MOXA** [d-fischer/twitch#26]
## Feature Request

Why I can't get follow time in https://d-fischer.github.io/twitch/reference/classes/ChannelFollow.html ?
There's also _data.created_at

**Comment by d-fischer** [comment]
Seems like I forgot this one.

For the sake of completeness, I added this in 1.3.6 and 2.0.0-pre.13.

Please consider using the Helix version instead though, which already had this before.

**Comment by T1MOXA** [comment]
I don't found the equivalent in the helix API

**Comment by d-fischer** [comment]
https://d-fischer.github.io/twitch@next/reference/classes/HelixUserAPI.html#symbol__getFollows

**Comment by T1MOXA** [comment]
Thanks
