### ISSUE TITLE
Failing to get value at "ChatBadgeList.badgeSetNames".

### ISSUE THREAD

**Issue by ichi0g0y** [d-fischer/twitch#29]
## Bug Report
`Cannot convert undefined or null to object` error when call `globalBadges.badgeSetNames`.
I am immature, but tried to send PR. #28 

### Code

```ts
const globalBadges = await twitchClient.badges.getGlobalBadges();
globalBadges.badgeSetNames.forEach(s => {
  const badgeSet = globalBadges.getBadgeSet(s);
  badgeSet.versionNames.forEach(v => {
    const version = badgeSet.getVersion(v);
    console.debug(JSON.stringify({
      imageUrl: version.getImageUrl(1),
      desc: version.description,
      clickUrl: version.clickUrl,
      clickAction: version.clickAction,
      title: version.title,
    }));
  });
});
```

### Expected behavior

call `ChatBadgeList.badgeSetNames` If normal return badge set names(string[]).

### Actual Behavior

but, `ChatBadgeList.badgeSetNames` :
```
return Object.keys(this._data.versions);
```
Isn't it correct to return a list of badge names rather than a list of versions?

I think the structure is as follows.

```
{
  broadcaster: {
    versions: {
      "1": {
        title: ~~,
        description: ~~,
        ...
      }
      ...
    }
  }
  ...
}
```

### Environment

- Version: 2.0.0
- Browser version: Google Chrome  72.0.3626.121
- Operating system: OSX Mojave

**Comment by d-fischer** [comment]
Fixed in ec24231.
