### ISSUE TITLE
Wrong type in TwitchChatClient onRitual method signature

### ISSUE THREAD

**Issue by lafiosca** [d-fischer/twitch#32]
## Bug Report

There's a typo [here](https://github.com/d-fischer/twitch/blob/a7dd0046730d18481c52e633ac67adeba956e796/packages/twitch-chat-client/src/ChatClient.ts#L270) in the TwitchChatClient `onRitual` method signature where an argument has the type `ChatRaidInfo` instead of `ChatRitualInfo`. I've created a simple PR to fix it, which I will link to this issue.

### Code

n/a

### Expected behavior

The type of the parameter `ritualInfo` should be `ChatRitualInfo`.

### Actual Behavior

The type of the parameter `ritualInfo` is `ChatRaidInfo`.

### Environment

n/a

**Comment by d-fischer** [comment]
The fix was published in `twitch-chat-client@2.3.2`.
