### ISSUE TITLE
Creating Client with invalid (but potentially refreshable token) fails at fetching scopes

### ISSUE THREAD

**Issue by gu3st** [d-fischer/twitch#36]
### Code

```js
        const refreshConfig = {
            clientSecret: Config.getTwitchClientSecret(),
            refreshToken: AccessTokenStore.getTwitchRefreshToken(),
            onRefresh: _tokenRefreshHandler /* function that handles storing tokens */
        };

        this.twitch = TwitchClient.withCredentials(Config.getTwitchClientId(),
            AccessTokenStore.getTwitchToken(),
            undefined, refreshConfig)
```

### Expected behavior

In the withCredentials call, I think it should refreshToken before fetching scopes if the token is expired

### Actual Behavior

withCredentials makes the assumption that the access token is not expired.  If it's expired, it fails when attempting to fetch scopes for the given key (as the key is expired).  Manually refreshing the key with the token refresh information works, so it _should_ be possible.

### Environment

- Version: 2.1.1
- Node version: 8.11
- Operating system: Linux Kernel 4.15

**Comment by d-fischer** [comment]
I just backported the fix to master after testing it on next. Thanks for reporting!
