### ISSUE TITLE
IRC client gets disconnected by the remote when too much data is received

### ISSUE THREAD

**Issue by jabbink** [d-fischer/twitch#40]
### Code

```javascript
// repeat 1000+ times
chatClient.join(_channelName).then(success);
```

### Expected behavior

My chat client joins all channels and stays in there.

### Actual Behavior

All channels are joined, but as soon as Twitch tries to send me **around** 0.6Mbps of chat messages, Twitch kills the connection (reason **1006** from what I could gather from the logs). I cannot quickly find the exact limit in the documentation of Twitch, but this behaviour is to be expected according to https://discuss.dev.twitch.tv/t/limits-on-irc-channels-join/16247/2  
Maybe I missed it in the documentation of this library, but is it possible to create separate connections that handle a couple of channels each, as apparently this send buffer is limited per IRC connection, unlike many other limits (e.g. 15 JOINs/PARTs per 15 seconds which is per IP address).

Coincidentally while adding error handling to restore from this failure I noticed that `chatClient.onDisconnect` is not implemented yet, or am I missing something. Right now I added code to abuse the "private" `chatClient._connection.onDisconnected` but I am not entirely sure if that would trigger either as it hasn't happened since.

### Environment

- Version: 2.3.5 (from npmjs)
- Node version: 11.x (dockerhub node:11-alpine)
- Operating system: Alpine (docker)

**Comment by jabbink** [comment]
After discussion about this issue on the discord channel (for anyone finding this at a later time):  
- Connection pooling is not planned for short-term 
![image](https://user-images.githubusercontent.com/2461972/58593716-f8469e80-826b-11e9-9f0b-f05b983dcbb0.png)
- `onDisconnected` from `ircv3` is forwarded and available

If you want connection pooling to different IRC connections, handle it yourself for now.

**Comment by Reprevise** [comment]
@d-fischer

It's been 2-3 years 😅

On a serious note, I think connection pooling would be a cool addition to this package.

**Comment by Geczy** [comment]
@jabbink are you still using twurple for irc connections? should i use something else?

how are you handling connection pooling yourself? im running into this issue where disconnects are happening way too frequently, and it's creating issues for my users in production. it takes way too long to join over 2k+ users rn

![image](https://user-images.githubusercontent.com/1036968/217913318-82717c72-2d2d-4776-a8e4-6e4e6b7791a0.png)

and these all in one day:

![image](https://user-images.githubusercontent.com/1036968/217913353-f994c4c2-0203-4f27-a99a-e1e9b60784c0.png)

**Comment by jabbink** [comment]
@Geczy I stopped the project I needed this for not too long ago.

I pooled connections by making a new chat client every `x` channels I wanted to join, keeping track which channel mapped to which client; that reduced the unexpected disconnects to basically 0.
