### ISSUE TITLE
Should return the display name

### ISSUE THREAD

**Issue by garyking** [d-fischer/twitch#46]
Simple bug. The following should be returning the display name, not ID.

https://github.com/d-fischer/twitch/blob/780a2077e8226e37c496112d95db31b6fa86b4b4/packages/twitch/src/API/Helix/Video/HelixVideo.ts#L57-L59

**Comment by garyking** [comment]
Thanks. Please release a new version of the package.

**Comment by d-fischer** [comment]
Fixed in 3.0.1.
