### ISSUE TITLE
`channel.id` is number or string, depending on the method

### ISSUE THREAD

**Issue by garyking** [d-fischer/twitch#51]
For `kraken.users.getFollowedChannels`, the `channel.id` value for each returned channel is `string`.

For `kraken.streams.getFollowedStreams`, `channel.id` is a `number`.

I think they should be the same type, regardless of which one is chosen.

**Comment by freaktechnik** [comment]
I'd assume that's due to kraken not having a consistent channelId type (sadly) and the lib just passing that on. I guess all the IDs should be forced to be a string, though.

**Comment by d-fischer** [comment]
Fix included in 3.1.1 - thanks for the report!
