### ISSUE TITLE
Missing `limit` param for `HelixVideoFilter`

### ISSUE THREAD

**Issue by garyking** [d-fischer/twitch#54]
`limit` isn't available in [HelixVideoFilter](https://d-fischer.github.io/twitch/reference/interfaces/HelixVideoFilter.html), but it is available for [`helix/get-videos`](https://dev.twitch.tv/docs/api/reference/#get-videos) (it's called `first`).

For `helix.getVideosByUser`, I'd like to get the max of 100 videos, rather than the default 20 videos.

**Comment by lclc98** [comment]
[HelixVideoFilter](https://github.com/d-fischer/twitch/blob/master/packages/twitch/src/API/Helix/Video/HelixVideoAPI.ts) extends [HelixPagination](https://github.com/d-fischer/twitch/blob/master/packages/twitch/src/API/Helix/HelixPagination.ts) so you should be able to use first still.

**Comment by garyking** [comment]
The `limit` option does indeed exist for `helix.getVideosByUser`, but it doesn't do anything, at least not for me when I tried it.

**Comment by d-fischer** [comment]
Fix included in 3.1.1 - thanks for the report!
