### ISSUE TITLE
twitch-webhooks documentation outdated

### ISSUE THREAD

**Issue by freaktechnik** [d-fischer/twitch#60]
The documentation refers to `subscribeToUserFollowsFrom`. However in the code there's actually `subscribeToFollowsFromUser` and `subscribeToFollowsToUser`.

**Comment by d-fischer** [comment]
Please send a link because I can't find any reference to that in the twitch-webhooks documentation.

**Comment by freaktechnik** [comment]
https://d-fischer.github.io/twitch/reference/classes/HelixWebHooksAPI.html

**Comment by d-fischer** [comment]
`HelixWebHooksAPI` is not the documentation of `twitch-webhooks` - the correct documentation you're looking for is https://d-fischer.github.io/twitch-webhooks/reference/classes/WebHookListener.html
