### ISSUE TITLE
Reading property scope from an AccessToken throws a TypeError

### ISSUE THREAD

**Issue by TheAkio** [d-fischer/twitch#63]
## Bug Report

When reading the property `scope` from an AccessToken received with the OAuth Authorization Code Flow it throws an error.

The Twitch API returns an array for the `scope` property while the code assumes it's a string and runs `scope.split(' ')` which results in an error because the function `split` doesn't exist on arrays.

EDIT: After looking a bit into the API Docs, it seems like Twitch always returns an array except for the case when a token is refreshed. I did not test out the refresh case yet, but it should not be overlooked when fixing this.

EDIT2: Just tested the refresh case. Also returns an array of scopes for me. So the Twitch docs are also not 100% up to date in that case.

### Code

```js
const express = require('express');
const twitch = require('twitch');

const app = express();

const clientID = '<Your client ID>';
const clientSecret = '<Your client Secret>';
const redirectUri = 'http://localhost:8381/twitch/authorize/callback'

const scopes = ['user_read', 'channel_editor'];
// Also try with no scopes. Gives another error
// const scopes = [];

app.get('/twitch/authorize', (req, res) => {
	res.redirect(`https://id.twitch.tv/oauth2/authorize?client_id=${clientID}&redirect_uri=${redirectUri}&response_type=code&scope=${scopes.join(' ')}&force_verify=true`)
});

app.get('/twitch/authorize/callback', async (req, res) => {
	const token = await twitch.default.getAccessToken(clientID, clientSecret, req.query.code, redirectUri);

	try {
		res.send(token.scope);
	} catch (e) {
		console.log(e);
		res.send(e.stack);
	}
});

app.listen(8381);
console.log('Started. Open http://localhost:8381/twitch/authorize');
```

### Expected behavior

It returns the array of scopes that was returned by the Twitch API.

### Actual Behavior

When reading the property `scope` from an AccessToken received with the OAuth Authorization Code Flow it throws the following error:

```
TypeError: this._data.scope.split is not a function
    at AccessToken.get [as scope] (/home/<redacted>/Workspaces/<redacted>/node_modules/twitch/lib/API/AccessToken.js:63:37)
```

### Environment

- Version: 3.4.4
- Node version: 10.15.1
- Operating system: Linux (Ubuntu 18.04.3 LTS)

**Comment by d-fischer** [comment]
Fix released with 3.5.0.

**Comment by TheAkio** [comment]
When I did a code search there were some places where it was still initialized as a string. You might want to check those too and change them to an empty array.

**Comment by d-fischer** [comment]
I already fixed these other places in the following commits. TypeScript catches these errors and I can't release a version that doesn't build.

**Comment by TheAkio** [comment]
Ahh okay, was only seeing that one commit and assumed that TS should have already complained and you might have forgotten about it.
