### ISSUE TITLE
Webhook for transaction created

### ISSUE THREAD

**Issue by InfinitySamurai** [d-fischer/twitch#64]
## Feature Request

Hey,

I'm looking at creating twitch extensions and one of the tricky things around them is knowing when bits have come through from the extension and double checking if they fail. The webhook for Transaction Created is what we would need to use and it appears that this package doesn't currently have the functionality to subscribe to this event.

https://dev.twitch.tv/docs/api/webhooks-reference#topic-extension-transaction-created

Willing to contribute to get this in, but will need some guidance on what needs doing.

**Comment by d-fischer** [comment]
Please refer to #55 to see what needs to be done :)

**Comment by d-fischer** [comment]
Fixed in 20e0aee and will be released as a new prerelease version soon.

**Comment by InfinitySamurai** [comment]
Thank you so much! Really appreciate it
