### ISSUE TITLE
New UserNotice found: communitypayforward & standardpayforward

### ISSUE THREAD

**Issue by crohde7707** [d-fischer/twitch#66]
## Feature Request

These two came across my logs today, figured you might want to add it!

- standardpayforward
- communitypayforward

**Comment by d-fischer** [comment]
I'm investigating the context of these messages. I have access to some examples for this, but not context. Are there any messages that always come before or after these? How do they look?

**Comment by crohde7707** [comment]
Based on what i can gather, it looks like these notices pop off when someone was gifted a sub to the channel at one point, and they gift a sub to someone else in the same channel. Don't have an idea on time frame between when a person was gifted and when they gifted. Same goes for community, just instead of them choosing someone specific to gift to, they choose to gift to someone random in the community

**Comment by d-fischer** [comment]
I know what they mean, I just need additional data on the actual notice format.

**Comment by crohde7707** [comment]
sorry, dont have any other information past that to help out, thats all that was captured :)

**Comment by d-fischer** [comment]
Added support for these in 3.6.0.
