### ISSUE TITLE
Some tests?

### ISSUE THREAD

**Issue by robhunt3r** [d-fischer/twitch#68]
## Feature Request
Well I think it could be nice to have a way to test if our listeners are working, some way to send fake data...

**Comment by d-fischer** [comment]
There has been some effort on the `testing` branch but due to lack of time it was kinda abandoned. Not sure when I can find enough time for it, actually.

Always feel free to contribute via PRs though. :)

**Comment by d-fischer** [comment]
If you're still interested in this, for chat, [fdgt](https://github.com/fdgt-apis/api) now exists.

**Comment by fabian-bickel** [comment]
I just used https://github.com/twitchdev/twitch-cli for testing with EventSub events and works nice after some problems how to call the cli for this libary.

**Comment by d-fischer** [comment]
With fdgt and Twitch CLI existing, I don't see value in implementing this anymore; thus, I'm closing this issue.
