### ISSUE TITLE
ChatClient UserInfo.userName is "tmi.twitch.tv"

### ISSUE THREAD

**Issue by AlcaDesign** [d-fischer/twitch#93]
## Bug Report

`ChatClient`'s `UserInfo` isn't working correctly. For example `msg.userInfo.userName` returns `tmi.twitch.tv` instead of the actual login.

### Code

```ts
chatClient.onSub((channel, user, subInfo, msg) => {
    console.log(msg.userInfo.userName); // "tmi.twitch.tv"
});
```

Example raw IRC:
```js
'@badge-info=;badges=premium/1;color=;display-name=LoginValue;emotes=;flags=;id=12345678-1234-4321-9876-0123456789ab;login=loginvalue;mod=0;msg-id=sub;msg-param-cumulative-months=1;msg-param-months=0;msg-param-should-share-streak=0;msg-param-sub-plan-name=Channel\\sSubscription\\s(somechannelname);msg-param-sub-plan=Prime;room-id=123456789;subscriber=1;system-msg=LoginValue\\ssubscribed\\swith\\sTwitch\\sPrime.;tmi-sent-ts=1580000000000;user-id=987654321;user-type= :tmi.twitch.tv USERNOTICE #somechannelname'
```

### Expected behavior

You should expect `"loginvalue"` instead of `"tmi.twitch.tv"`.

### Actual Behavior

The prefix is not fully populated with the correct value for the user, so you get tmi.twitch.tv instead of something else. (It's just `tmi.twitch.tv` instead of `alca!alca@alca.tmi.twitch.tv` or whatever)
```js
/* ... */
_prefix: { nick: 'tmi.twitch.tv' },
/* ... */
```

### Environment

- Version: `twitch-chat-client@3.7.1`
- Node version: 13.8.0
- Operating system: Windows 10, using Ubuntu 18.04 via WSL

**Comment by d-fischer** [comment]
Fixed in ff55ef4, to be released some time this week.
